# Aviation Accidents Analysis

You are part of a consulting firm that is tasked to do an analysis of commercial and passenger jet airline safety. The client (an airline/airplane insurer) is interested in knowing what types of aircraft (makes/models) exhibit low rates of total destruction and low likelihood of fatal or serious passenger injuries in the event of an accident. They are also interested in any general variables/conditions that might be at play. Your analysis will be based off of aviation accident data accumulated from the years 1948-2023. 

Our client is only interested in airplane makes/models that are professional builds and could potentially still be active. Assume a max lifetime of 40 years for a make/model retirement and make sure to filter your data accordingly (i.e. from 1983 onwards). They would also like separate recommendations for small aircraft vs. larger passenger models. **In addition, make sure that claims that you make are statistically robust and that you have enough samples when making comparisons between groups.**


In this summative assessment you will demonstrate your ability to:
- **Use Pandas to load, inspect, and clean the dataset appropriately.**
- **Transform relevant columns to create measures that address the problem at hand.**
- conduct EDA: visualization and statistical measures to systematically understand the structure of the data
- recommend a set of airplanes and makes conforming to the client's request and identify at least *two* factors contributing to airplane safety. You must provide supporting evidence (visuals, summary statistics, tables) for each claim you make.

### Make relevant library imports

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

## Data Loading and Inspection

### Load in data from the relevant directory and inspect the dataframe.
- inspect NaNs, datatypes, and summary statistics

In [3]:
df = pd.read_csv('Accidents.csv')

In [4]:
#Top 5 columns
df.head()

,Date,StateOfOccurrence,Location,Model,Registration,Operator,StateOfOperator,StateOfRegistry,FlightPhase,Class,...,InjuryLevel,TypeDesignator,Helicopter,Airplane,Engines,EngineType,Official,OccCats,Risk,Year
0,"""2008-01-03T00:00:00.000Z""",USA,Oklahoma City,PILATUS PC12,N398J,NaN,NaN,USA,Standing,Accident,...,Fatal,PC12,False,True,1,Turboprop,NaN,"[""RAMP""]",RS,2008
1,"""2008-01-05T00:00:00.000Z""",USA,Kodiak,PIPER PA31P 350,N509FN,Servant Air,NaN,USA,Take-off,Accident,...,Fatal,PA47,False,True,1,Jet,NaN,"[""LOC-I"",""SCF-NP""]",LOC-I,2008
2,"""2008-01-07T00:00:00.000Z""",USA,DeLand,NaN,N801DS,NaN,NaN,USA,En route,Accident,...,NaN,RAV3,False,True,1,Piston,NaN,"[""SCF-PP"",""F-NI""]",SCF,2008
3,"""2008-01-08T00:00:00.000Z""",USA,NaN,Piper Aircraft Inc PA-46 Malibu,N295S,Alan Robinson,NaN,USA,En route,Accident,...,NaN,PA46,False,True,1,Piston,NaN,[],TURB,2008
4,"""2008-01-08T00:00:00.000Z""",USA,NaN,Robinson Helicopter Company R22,N179SH,Silver State Helicopters Ltd,NaN,USA,En route,Accident,...,Serious,R22,True,False,1,Piston,NaN,[],NaN,2008

In [5]:
#Bottom 5 column
df.tail()

,Date,StateOfOccurrence,Location,Model,Registration,Operator,StateOfOperator,StateOfRegistry,FlightPhase,Class,...,InjuryLevel,TypeDesignator,Helicopter,Airplane,Engines,EngineType,Official,OccCats,Risk,Year
4541,"""2020-10-16T00:00:00.000Z""",USA,NaN,Robinson Helicopter Company R44,N500DL,Spring Mountain Raceway LLC,NaN,USA,Unknown,Accident,...,NaN,R44,True,False,1,Piston,NaN,[],NaN,2020
4542,"""2020-10-18T00:00:00.000Z""",USA,NaN,Robinson Helicopter Company R22,N566BC,Blue Ridge Helicopters Inc,NaN,USA,Unknown,Accident,...,NaN,R22,True,False,1,Piston,NaN,[],NaN,2020
4543,"""2020-10-18T00:00:00.000Z""",USA,NaN,Robinson Helicopter Company R44,N31136,Midwestern Helicopter LLC,NaN,USA,Take-off,Accident,...,NaN,R44,True,False,1,Piston,NaN,[],NaN,2020
4544,"""2020-10-20T00:00:00.000Z""",USA,NaN,Twin Commander Aircraft LLC Twin Commander,N607MM,Central Air Southwest,NaN,USA,Standing,Accident,...,NaN,AC11,False,True,1,Piston,NaN,[],RS,2020
4545,"""2020-10-21T00:00:00.000Z""",USA,NaN,Bell Bell 206,N716VL,AirCam National Helicopter Services Inc,NaN,USA,En route,Accident,...,NaN,EBOY,False,True,1,Piston,NaN,[],TURB,2020

## Data Cleaning

In [6]:
#Check info
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4546 entries, 0 to 4545
Data columns (total 24 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Date                 4546 non-null   object
 1   StateOfOccurrence    4546 non-null   object
 2   Location             1814 non-null   object
 3   Model                4431 non-null   object
 4   Registration         4546 non-null   object
 5   Operator             3639 non-null   object
 6   StateOfOperator      344 non-null    object
 7   StateOfRegistry      4545 non-null   object
 8   FlightPhase          4446 non-null   object
 9   Class                4546 non-null   object
 10  Fatalities           4432 non-null   float64
 11  Over2250             4546 non-null   bool
 12  Over5700             4310 non-null   object
 13  ScheduledCommercial  3642 non-null   object
 14  InjuryLevel          1386 non-null   object
 15  TypeDesignator       4546 non-null   object
 16  Helicopter           4286 non-null   object
 17  Airplane             4546 non-null   bool
 18  Engines              4546 non-null   int64
 19  EngineType           4546 non-null   object
 20  Official             315 non-null    object
 21  OccCats              4546 non-null   object
 22  Risk                 3464 non-null   object
 23  Year                 4546 non-null   int64
dtypes: bool(2), float64(1), int64(2), object(19)
memory usage: 790.4+ KB

In [7]:
#Deine shape
df.shape

(4546, 24)

In [8]:
#stats
df.describe().T

,count,mean,std,min,25%,50%,75%,max
Fatalities,4432.0,0.388764,1.305783,0.0,0.0,0.0,0.0,50.0
Engines,4546.0,1.451826,0.533158,1.0,1.0,1.0,2.0,4.0
Year,4546.0,2013.193357,3.745097,2008.0,2010.0,2012.0,2017.0,2020.0

In [9]:
#clear stats on categorical columns
df.describe(include='O').T

                    count unique                              top  freq
Date                 4546   2688       "2011-03-19T00:00:00.000Z"    14
StateOfOccurrence    4546      1                              USA  4546
Location             1814   1346                         New York    11
Model                4431    752  Robinson Helicopter Company R44   258
Registration         4546   4397                           N852AT     5
Operator             3639   2320              Private US Operator   221
StateOfOperator       344     25                              USA   303
StateOfRegistry      4545     24                              USA  4475
FlightPhase          4446      9                          Landing  1305
Class                4546      1                         Accident  4546
Over5700             4310      2                            False  3529
ScheduledCommercial  3642      2                            False  3175
InjuryLevel          1386      4                            Fatal   771
TypeDesignator       4546    429                              R44   265
Helicopter           4286      2                            False  3164
EngineType           4546      3                           Piston  2406
Official              315      1                             True   315
OccCats              4546    176                               []  3555
Risk                 3464     20                               RS  2106

In [10]:
df.columns

Index(['Date', 'StateOfOccurrence', 'Location', 'Model', 'Registration',
       'Operator', 'StateOfOperator', 'StateOfRegistry', 'FlightPhase',
       'Class', 'Fatalities', 'Over2250', 'Over5700', 'ScheduledCommercial',
       'InjuryLevel', 'TypeDesignator', 'Helicopter', 'Airplane', 'Engines',
       'EngineType', 'Official', 'OccCats', 'Risk', 'Year'],
      dtype='object')

In [11]:
#finding unique values
for cln in df.columns:
    uni_value = df[cln].unique()
    print(f'{cln}\n {uni_value}\n\n')

Date
 ['"2008-01-03T00:00:00.000Z"' '"2008-01-05T00:00:00.000Z"'
 '"2008-01-07T00:00:00.000Z"' ... '"2020-10-18T00:00:00.000Z"'
 '"2020-10-20T00:00:00.000Z"' '"2020-10-21T00:00:00.000Z"']


StateOfOccurrence
 ['USA']


Location
 ['Oklahoma City' 'Kodiak' 'DeLand' ...
 'ca 11 km NE of Victoria Regional Airport, TX (VCT)'
 ' Visalia Airport, CA (VIS)' 'near Scottsbluff, NE']


Model
 ['PILATUS PC12' 'PIPER PA31P 350' nan 'Piper Aircraft Inc PA-46 Malibu'
 'Robinson Helicopter Company R22' 'AIRBUS A319' 'CESSNA 340'
 'Bell Bell 206' 'BOEING 757 200' 'CANADAIRREGIONAL JET SERIES 100/200'
 'BEECH 1900' 'Robinson Helicopter Company R44' 'CESSNA 208' 'RAYTHEON'
 'NORTH AMERICAN' 'BEECH G58' 'PIPER PA46 500TP'
 'Epic Aircraft LT/ Dynasty' 'Piper Aircraft Inc PA-31T' 'GRUMMAN G21'
 'Bell OH-58' 'LEARJET 35' 'BEECH 90' 'Rockwell International Sabreliner'
 'CESSNA 525 CITATIONJET' 'ROCKWELL' 'Piper Aircraft Inc PA-31 Navajo'
 'Piper Aircraft Inc PA-34 Seneca' 'DE HAVILLAND DHC8'
 'SWEARINGENMERLIN IV A' 'Airbus Helicopters H125 / AS350'
 'DE HAVILLAND DHC2 I' 'Piper Aircraft Inc PA-44 Seminole'
 'MD Helicopters Inc MD500 / Hughes 369' 'CESSNA 425 NO SERIES EXISTS'
 'PIPER PA23 250' 'EMBRAER EMB145 ER' 'CESSNA 414' 'EMBRAER ERJ170'
 'Beechcraft Corp Baron (Beech 58)' 'BOEING 737' 'BEECH 55'
 'Sikorsky (Schweizer) Hughes 269' 'CESSNA' 'CESSNA 500 CITATION'
 'SIKORSKY S58' 'CESSNA 402' 'AIR TRACTOR AT602 NO SERIES EXISTS'
 'AIR TRACTOR AT301' 'GRUMMAN G164' 'AYRES' 'MD Helicopters Inc MD 600'
 'SCHWEIZER' 'PIPER PA24' 'Bell UH-1' 'CESSNA 750 NO SERIES EXISTS'
 'RAYTHEON HAWKER' 'FAIRCHILDSA227 III' 'BOEING 737 800' 'SIAI MARCHETTI'
 'CANADAIR CL600 1A11 600' 'Beechcraft Corp Beech 2000 Starship'
 'CESSNA 310' 'EMBRAER EMB110' 'WEATHERLY 620' 'CESSNA 560 CITATION V'
 'Enstrom Helicopter Corporation Enstrom F-28' 'CESSNA 421'
 'AIR TRACTOR AT402' 'CCF' 'AIR TRACTOR AT502' 'DE HAVILLAND'
 'NORTH AMERICAN SNJ' 'BEECH 65' 'Sikorsky Aircraft Corporation S-61'
 'ROCKWELL 680' 'Airbus Helicopters H135 / EC135'
 'Beechcraft Corp Beech 99' 'Hughes Helicopters MD500 / Hughes 369'
 'AIR TRACTOR AT401' 'Fairchild-Hiller Corp FH-1100' 'BEECH 200'
 'HAWKER SIDDELEY' 'Pilatus Flugzeugwerke AG PC-12' 'SOCATA TBM700'
 'MITSUBISHI' 'AYRES S2R600 T660' 'SIKORSKY S76' 'ROCKWELL 690' 'BEECH 18'
 'Bell Bell 407' 'MCDONNELL DOUGLAS DC10' 'BEECH 100' 'DE HAVILLAND DHC6'
 'BOEING 717 200' 'BEECH 99' 'AERO VODOCHODY' 'SNOW'
 'Enstrom Helicopter Corporation Enstrom 480' 'BOEING 767 200'
 'Cessna Aircraft Company CJ3' 'CESSNA 441 NO SERIES EXISTS' 'EAGLE DW1'
 'PIPER PA31T 1' 'Diamond Aircraft Industries GmbH DA42' 'PZL SWIDNIK'
 'Eclipse Aerospace Inc Eclipse 500' 'SWEARINGEN SX300' 'BAE BAE125'
 'CESSNA 551 CITATION II' 'SIKORSKY S61 N'
 'Enstrom Helicopter Corporation Enstrom 280' 'MORANE SAULNIER MS760 A'
 'AIR TRACTOR AT802' 'BOEING 777 300' 'AIR TRACTOR AT400' 'VERTOL'
 'DE HAVILLAND DH82 A' 'SWEARINGEN' 'CONVAIR 580' 'LOCKHEED P2V'
 'LEARJET 25' 'PIPER PA60 602P' 'LEARJET 60' 'AEROSPATIALE SA365'
 'CESSNA 320' 'Cessna Aircraft Company Citation' 'BELL 222'
 'PIPER PA28 201T' 'Airbus A320' 'CASA C212' 'Vulcanair P.68'
 'CESSNA 680 NO SERIES EXISTS' 'Bombardier (Canadair) CRJ Regional Jet'
 'PIPER PA60' 'PIPER PA28' 'BEECH 35' 'DASSAULT' 'BEECH 60'
 'Bell Bell 222' 'MCDONNELL DOUGLASDC-9-50' 'MITSUBISHI MU300'
 'Beechcraft Corp Beech 1900' 'CANADAIR CL600 2A12 600'
 'Cessna Aircraft Company Cessna 402' 'KAMAN K1200'
 'DASSAULT MYSTERE FALCON20' 'BELL 407' 'BOEING747-100/200 747'
 'MCDONNELL DOUGLASMD80 SERIES' 'BOEING 757 300' 'LEARJET 45'
 'AEROSPATIALE AS350' 'AIRBUS A320' 'ATR ATR42 300' 'ROBINSON R22'
 'Boeing (McDonnell-Douglas) DC-3' 'DE HAVILLAND DHC8 400' 'PIPER PA31T'
 'GRUMMAN' 'PIPER PA42' 'LEARJET 55' 'Beechcraft Corp King Air 90'
 'Sikorsky Aircraft Corporation S-76' 'PIPER PA31' 'CURTISS WRIGHT P40'
 'SIKORSKY S64' 'Embraer 175' 'DE HAVILLAND DHC2 III' 'BOEING 767 300'
 'Cessna Aircraft Company Cessna 441' 'MCDONNELL DOUGLASDC-3 DAKOTA/C-47'
 'Rockwell International Turbo Commander'
 'Cessna Aircraft Company Cessna 421' 'MCDONNELL DOUGLAS DC10 30'
 'Piaggio Aerospace P180 Avanti' 'EMBRAER EMB135'
 'Airbus Helicopters H120' 'CESSNA 404 NO SERIES EXISTS' 'YAKOVLEV YAK11'
 'AGUSTA A109' 'AEROSPATIALE AS350 B2' 'MCDONNELL DOUGLAS'
 'EMBRAER ERJ175' 'NOORDUYN UC64' 'BOEING 737 300' 'SIKORSKY S61'
 'BELL 212' 'SIKORSKY S55' 'DE HAVILLAND DHC8 300'
 'De Havilland Canada DHC-8' 'Airbus Helicopters H145 / EC145'
 'Britten-Norman Aircraft Ltd BN-2' 'Airbus Helicopters Bo105'
 'Beechcraft Corp King Air 200' 'LEARJET 36' 'GRUMMAN G44' 'SHORT SC7'
 'AEROSTAR AEROSTAR601' 'MD Helicopters Inc MD 520N' 'AGUSTA A119'
 'BOEING 767 400' 'MCDONNELL DOUGLAS MD90 30' 'GRUMMAN G111'
 'Fairchild (Swearingen) Merlin III'
 'Mitsubishi Aircraft Corporation MU-2' 'Daher-Socata TBM 700 / 850 / 900'
 'SWEARINGEN SA226 TC' 'BELL 206' 'PIPER PA32' 'HUGHES 369' 'VANS RV8'
 'AIRBORNE XT582' 'ERCOUPE G' 'VANS RV4' 'CESSNA 182' 'MOONEY M20'
 'MITSUBISHI MU2B 60' 'CESSNA T41' 'LUSCOMBE 8' 'RAYTHEON1900'
 'BELL 47G 4A' 'AEROSTAR AEROSTAR601 P' 'CESSNA 150' 'BELL 206 L'
 'AEROSPATIALE' 'SCHWEIZER SGS232' 'CIRRUS SR22 NO SERIES EXISTS'
 'CIRRUS SR20 NO SERIES EXISTS' 'PIPER PA25' 'NANCHANG CJ6 A' 'BELLANCA'
 'YAKOVLEV YAK52' 'EUROCOPTER EC135' 'EMBRAER EMB120' 'AIR FOUGA CM170'
 'CESSNA 210' 'PIPER PA46' 'BOMBARDIER BD700 1A11' 'CESSNA 185'
 'GRUMMAN AA5' 'BEECH 24' 'PIAGGIO P180 AVANTI' 'EIPPER QUICKSILVER'
 'BOEING 747 400' 'CESSNA T303 NO SERIES EXISTS' 'EVEKTOR AEROTECHNIK'
 'BEECH 36' 'CESSNA 206' 'MD HELICOPTER 500' 'TECNAM P92 EA' 'KAWASAKI'
 'BRITTEN NORMAN BN2A' 'ROLLADEN SCHNEIDER LS4' 'LANCAIR IV P'
 'PROGRESSIVE AERODYNE SEAREY NO SERIES EXISTS' 'Learjet 35A' 'CESSNA 152'
 'CESSNA 120 NO SERIES EXISTS' 'PIPER PA34' 'DIAMOND DA20'
 'BALLOON WORKS FIREFLY8B' 'MITSUBISHI MU2' 'VANS RV6 A' 'MAULE M7 235'
 'VANS RV6' 'MAULE M5 220' 'SAAB 340' 'CESSNA 170' 'LAKE LA4'
 'GRUMMAN G1159' 'CHAMPION 7GC' 'DENNEY KITFOX' 'PIPER PA44' 'PIPER J3C'
 'GLOBE' 'AEROSPATIALE SA366' 'BEECH 76 NO SERIES EXISTS' 'INTERSTATE S1A'
 'CESSNA 305' 'SCHLEICHER ASW20' 'HILLER UH12' 'PIPER PA18' 'ROBINSON R44'
 'CHAMPION 7GCB' 'CHAMPION' 'RUTAN LONGEZ' 'AYRES S2R T'
 'BOMBARDIERCL-600 Regional Jet CRJ-1000' 'SCHWEIZER SGS136'
 'DASSAULT FALCON10' 'PIETENPOL AIRCAMPER' 'AERONCA' 'CESSNA 140'
 'RANS S6 ES' 'VANS RV4 UNDESIGNATED SERIES' 'PITTS S2' 'BELL 206 B'
 'PIPER PA22' 'PIPER PA20' 'EIPPER QUICKSILVER MXII' 'VANS RV9 A'
 'CESSNA 180' 'MOONEY M20M' 'PIPER PA28 140' 'STEARMAN A75 L300'
 'AIRBUS A330 300' 'CESSNA 337' 'AIRBUS A321' 'CHAMPION 7EC'
 'Air Tractor Inc AT-602' 'STEARMAN B75 N1' 'BELL 47' 'CORBEN BABYACE'
 'RANS S6' 'AIR CREATION' 'LINDSTRAND LBL120A' 'CESSNA 401' 'LUSCOMBE 11A'
 'PIPER PA11' 'Boeing 737-832 (WL)' 'AERONCA 7AC' 'PIPER J3C 65'
 'PILATUS P3 NO SERIES EXISTS' 'BELL UH1H' 'HILLER UH12E' 'CESSNA 175'
 'STEARMAN A75 N1' 'DE HAVILLAND L20A' 'BEECH 23 C23' 'LANCAIR IV'
 'ZENITH CH601 XL' 'DIAMOND DA20 C1' 'BEECH 33' 'AVIAT A1 B'
 'SCHLEICHER ASW27' 'SCHLEICHER ASW20L NO SERIES EXISTS' 'BRANTLY B2'
 'CESSNA 172 F' 'ERCOUPE 415' 'GRUMMAN G164 B' 'SCHWEIZER SGS126'
 'PIPER PA28R' 'CESSNA 172 N' 'ZENAIR STOL CH701' 'MAX HOLSTE MH1521'
 'PIPER PA14' 'NORD 3200' 'CESSNA 188' 'AMERICAN AVIATION AA1'
 'Air Tractor Inc AT-500' 'THORP T18' 'AVID' 'LANCAIR 320'
 'GULFSTREAM GIV' 'Beechcraft Corp Premier I' 'AEROSPATIALE AS350 B3'
 'PIPER PA36' 'ZENAIR CH601 HD' 'AIR TRACTOR AT602' 'SCHWEIZER SGS233'
 'LINDSTRAND LBL69A' 'STEARMAN PT13 B' 'CESSNA 177' 'GLASER DIRKS DG300'
 'Fairchild C-123K Provider' 'Daher-Socata Kodiak 100'
 'Dassault Aviation Falcon 900' 'Air Tractor Inc AT-802'
 'Viking Air DHC-3' 'Scaled Composites LLC White Knight Two (Model 348)'
 'Piper Aircraft Inc PA-42' 'Airbus Helicopters Lama SA315B'
 'Embraer Phenom 100' 'Hawker Beechcraft 1900' 'Airbus Helicopters AS355'
 'Bell Bell 412' 'Bombardier (Canadair) CRJ900 Regional Jet'
 'Cessna Aircraft Company Cessna 425' 'Airbus Helicopters H130 / EC130'
 'Cessna Aircraft Company Citation II'
 'Gulfstream Aerospace Corp Gulfstream IV' 'BOMBARDIER'
 'Cessna Aircraft Company Cessna 404' 'Beechcraft Corp King Air 100'
 'Cessna Aircraft Company Cessna 340' 'Bombardier (Learjet) Learjet 25'
 'Bombardier (Canadair) CRJ700 Regional Jet' 'BEECH 300' 'Tecnam P2006'
 'MBB BK117' 'BELLANCA 1419 3' 'LANCAIR LC41 550FG' 'MAULE M4'
 'ROCKWELL S2R' 'RYAN PT22' 'BEECH 23' 'PIPER PA18 150' 'DIAMOND DA20 A1'
 'CONVAIR 340' 'CESSNA 182 R' 'Dassault Aviation Falcon 20/200'
 'MOONEY M20R' 'PIPER PA30' 'MCDONNELL DOUGLAS 369 F'
 'MCDONNELL DOUGLAS MD90' 'POTEZ AIR FOUGA CM170' 'Bombardier CRJ200'
 'BELLANCA 1419' 'CHAMPION 8GCBC' 'AIRBORNE XT912' 'TAYLORCRAFT BC12'
 'MOONEY M20K' 'REARWIN 8135' 'DOUGLAS DC9 80' 'MOONEY M20F'
 'EMBRAER-ERJ190-100IGW' 'CESSNA 195' 'LANCAIR 360' 'ENSTROM F28'
 'BAC 167' 'GREAT LAKES' 'BEECH 35 G35' 'ERJ-145(HARBIN EMBRAER)'
 'RAND ROBINSON KR2' 'DOUGLAS' 'EUROCOPTER EC130' 'WACO UPF7'
 'GLASER DIRKS DG500 TRAINER' 'CESSNA 414 UNDESIGNATED SERIES'
 'BELLANCA 1413 2' 'DE HAVILLAND DHC3' 'BELL 230' 'TECNAM' 'CESSNA P210 N'
 'GLASFLUGEL H301' 'AIRBUS A300 600' 'CIRRUS SR22' 'CESSNA 188 B'
 'GROB G102 ASTIR CS' 'PIPER PA38' 'GULFSTREAM' 'CESSNA 172' 'RANS S12 XL'
 'NORTH AMERICAN NAVION' 'AVIAT A1' 'BELL 47G' 'PIPER PA12' 'LET L33'
 'BOMBARDIER-CRJ-700' 'AIRBUS A380' 'PZL MIELEC AN2' 'BOEING 777 200'
 'HEINTZ ZENITH' 'BEECH 45' 'RANS S12' 'WITTMAN W8'
 'Cessna Aircraft Company Cessna 414' 'BOEING 707' 'GULFSTREAM GV'
 'Bombardier CRJ-900' 'Douglas DC-6BF' 'Cessna Aircraft Company CJ2'
 'Bell Bell 212' 'Boeing 767-332ER (WL)'
 'Sikorsky Aircraft Corporation S-55' 'Sikorsky Aircraft Corporation S-58'
 'Cessna Aircraft Company 208' 'Bell Bell 205'
 'Robinson Helicopter Company R66' 'Bombardier (Learjet) Learjet 60'
 'Airbus A320-211' 'Cessna Aircraft Company Citation S/II'
 'Cessna Aircraft Company Cessna 401' 'Airbus Helicopters BK117'
 'Boeing 747' 'Bell Bell 230' 'Boeing 757-351 (WL)' 'Boeing 737-732 (WL)'
 'CESSNA 650 CITATION VII' 'Leonardo (PZL-Swidnik) SW-4' 'DHC8'
 'Cessna Aircraft Company Citation V' 'Reims Aviation S.A. 406 Caravan II'
 'Gulfstream Aerospace Corp Gulfstream G150' 'An-124'
 'Bombardier (Learjet) Learjet 35' 'CL-600'
 'Bombardier (Learjet) Learjet 31' 'Bombardier (Learjet) Learjet 55'
 '737-800' '737-700' 'A321' '767-400' 'Embraer 170' 'Bell AH-1'
 'Mitsubishi Aircraft Corporation MU-300 Diamond' 'DHC8-400' 'A319'
 'Cessna Aircraft Company Citation XLS' 'Viking Air SC.7 Skyvan'
 'Viking Air Short 360 (SD3-60)'
 'Bombardier (Canadair) Challenger 600 / 601 / 604 / 605' '747-400' '135'
 'Lockheed SP-2H Neptune' 'Lockheed P-2H Neptune' 'Bell Bell 427'
 '757-200' 'A320' 'Cessna Aircraft Company Citation Excel'
 'Israel Aerospace Industries Ltd Westwind'
 'Hawker Beechcraft Corp Hawker 400 / Beechjet 400' 'DHC-8-402Q Dash 8'
 'Viking Air DHC-2' 'Airbus Helicopters Alouette 2'
 'Leonardo (AgustaWestland) AW109' 'CRJ-700' 'EMB-170' 'Bell Bell 214'
 'AIRBUS A330' 'Cessna Aircraft Company CJ1' 'A330-300'
 'Bombardier (Learjet) Learjet 36' '717-200' '737-300'
 'Leonardo (AgustaWestland) AW119' 'Leonardo (AgustaWestland) AW139'
 'Pilatus Flugzeugwerke AG PC-6 Turbo Porter'
 'Fairchild (Swearingen) Metro' 'CRJ'
 'Cessna Aircraft Company Citation Encore' 'MD-11' 'EMB-145' 'Boeing 777'
 'McDonnell Douglas MD-11' 'Embraer ERJ-145' 'EMBRAER ERJ190' 'BOEING 757'
 'Boeing 757' 'BEECH 1900 C' 'CESSNA 402 C' 'Airbus A321'
 'Embraer EMB-170' 'Bombardier CRJ-200' 'Bombardier Dash 8'
 'McDonnel Douglas MD-88' 'Kaman Aerospace K-1200' 'Boeing 737'
 'Canadair CL-600-2A12 Challenger 601' 'EMBRAER' 'Airbus A300'
 'Beechcraft 1900' 'Airbus Helicopters AS365'
 'Cessna 525A CitationJet CJ2+' 'Embraer EMB-500 Phenom 100' 'Boeing 767'
 'Beechcraft Corp King Air 350' 'Douglas C-118A Liftmaster (DC-6A)'
 'CESSNA 208 B' 'Swearingen Metro' 'Bombardier (Learjet) Learjet 24'
 'Bell Bell 430' 'Gulfstream G200' 'McDonnell Douglas MD-88'
 'Douglas DC-9' 'Cessna 500 Citation I'
 'Cessna Aircraft Company Citation Sovereign' 'EMBRAER EMB140'
 'Pacific Aerospace Limited 750XL' 'Cessna Aircraft Company CJ4'
 'Airbus A330' 'Cessna 525 CitationJet CJ1' 'Boeing 737 NG'
 'Embraer ERJ-140' 'DHC-3T Texas Turbine Otter'
 'Swearingen SA226-AT Merlin IV' 'Cessna 208B Grand Caravan'
 'Gulfstream Aerospace Corp Gulfstream III' 'DHC-6 Twin Otter 300'
 'Embraer 145' 'Boeing 757-223 (WL)' 'Embraer Phenom 300'
 'AIRBUS A340 200' 'Hawker Beechcraft Corp 125/ Hawker'
 'Boeing 737-330 (SF)' 'Boeing 757-232 (WL)'
 'MD Helicopters Inc MD900 / MD902' 'CESSNA 441'
 'Viking Air DHC-6 Twin Otter' 'Embraer 190' 'BEECH 350'
 'Cessna 208B Super Cargomaster' 'GULFSTREAM GV SP G550'
 'EUROCOPTER EC130 B4' 'CESSNA 414 A' 'MBB BK117 C' 'EUROCOPTER'
 'Hawker Beechcraft Corp Hawker 4000' 'LEARJET 35 A'
 'SHORT SD360 SHERPA VARIANT100' 'Beech 99' 'CANADAIR CL600 2B16 600'
 'IAI 1125' 'CESSNA 560 XL' 'BEECH C90' 'DASSAULT FALCON2000'
 'Cessna 550 Citation II' 'Bombardier BD-100-1A10 Challenger 300'
 'Cessna 525 CitationJet' 'Boeing 787' 'HAWKER SIDDELEY HS125'
 'Airbus A319' 'SINO SWEARINGEN SJ30' 'HAWKER 400'
 'Canadair CL-600-2C10 Regional Jet CRJ-702' 'EMBRAER ERJ170 100'
 'CESSNA 525' 'MCDONNELL DOUGLAS MD88 80' 'BOEING 737 700'
 'Guimbal Helicopters Cabri G2'
 'Enstrom Helicopter Corporation Enstrom TH180' 'LOCKHEED 382 G'
 'SWEARINGEN SA226 TB' 'EMBRAER EMB145 MP' 'BEECH 400 A'
 'Canadair CL-600-2B19 Regional Jet CRJ-200ER'
 'Cessna Aircraft Company Citation X' 'BOMBARDIER CL600 2B19 100'
 'Antonov An-2R' 'Airbus A321-211' 'AIRBUS A320 200' 'AIRBUS A319 100'
 'Bell Bell 429' 'BOEING 737 900' 'Cessna Aircraft Company Citation Ultra'
 'AIRBUS A321 200' 'Bell Bell 525' 'DIAMOND DA40'
 'Beechcraft B200 Super King Air' 'Beechcraft C99 Commuter' 'BELL 429'
 'BEECH' 'AGUSTA A109 S' 'DE HAVILLAND DHC8 200' 'Cessna 208 Caravan I'
 'AIR TRACTOR AT502 B' 'NAMC YS-11' 'Airbus A380' 'Boeing 737-823 (WL)'
 'SWEARINGEN SA227 AC' 'Beechcraft Corp Beech Duchess (Beech 76)'
 'Beechcraft Corp King Air 300' 'Boeing 737-700' 'De Havilland Dash 8'
 'Airbus A319-100' 'Boeing (McDonnell-Douglas) MD-80' 'Boeing MD-83'
 'Swearingen SA226-TC Metro II' 'Beechcraft B200 King Air'
 'Embraer ERJ190' 'Beechcraft 99A Airliner'
 'Viking Air Short 330 (SD3-30)' 'Boeing 757-200'
 'Gulfstream Aerospace Corp G-73' 'Cessna Aircraft Company Cessna 303'
 'Airbus A321-200' 'Bombardier CL 600 2C10' 'Embraer ERJ 170'
 'Fairchild (Swearingen) Merlin II' 'Sikorsky Aircraft Corporation S-97'
 'Airbus 330-300' 'Lockheed P2V-5F Neptune' 'Boeing B737-800'
 'Aerostar Aircraft Corporation Aerostar' 'Bombardier CRJ700' 'Cessna 680'
 'Boeing MD90' 'Boeing 767-375ER' 'Embraer EMB-120ER Brasilia'
 'Airbus A321-231' 'Boeing 737-800' 'Boeing B737-700' 'Boeing B767-300ER'
 'Airbus A330-343' 'Boeing B777' 'Boeing MD88' 'Embraer ERJ 700'
 'Boeing DC-9' 'BOEING 777' 'Swearingen SA227-AT Merlin IVC'
 'Twin Commander Aircraft LLC Twin Commander' 'Sikorsky (Schweizer) 269D'
 'AIRBUS A330 323' 'CASA C-212 Aviocar 200'
 'Cessna Aircraft Company Citation III' 'BOEING 737 7H4'
 'Bombardier CRJ-900LR (CL-600-2D24)'
 'BOEING 767 332; BOMBARDIER CL600 2D24' 'BOEING 737-8H4'
 'Boeing (McDonnell-Douglas) MD-11' 'Mahindra Aerospace GA10'
 'BOEING 787-9' 'Boeing 777 223' 'Curtiss C-46F-1-CU'
 'Douglas C-47B (DC-3)' 'Mcdonnell Douglas MD88'
 'Cessna 560 Citation Encore' 'Beechcraft B300 King Air 350'
 'Airbus A321-271N' 'Cessna Aircraft Company Citation Mustang'
 'British Aerospace BAe-125-700A' 'Embraer EMB-120 Brasilia'
 'Dassault Aviation Falcon 50' 'Beech 1900'
 'Cessna Aircraft Company Citation Latitude' 'Bombardier CL 600 2B19'
 'Embraer ERJ190-100' 'Airbus A320-200' 'Boeing 727-200' 'Boeing 787-8'
 'Convair C-131B Samaritan' 'Embraer ERJ170' 'Boeing B777-200'
 'Sikorsky Aircraft Corporation S-70' 'Embraer EMB145'
 'Boeing 737-800 & Boeing 757-300'
 'Bombardier CL 600 2C10 & Bombardier CL600 2D24'
 'Bombardier CL-600-2C10 Regional Jet CRJ-702ER'
 'Bombardier CL-600-2D24 Regional Jet CRJ-900LR' 'McDonnell Douglas MD88'
 'Boeing 737-900' 'Beechcraft Corp Beech Duke (Beech 60)'
 'Mahindra Aerospace GA8' 'Beechcraft B300 King Air 350i' 'Boeing 767-300'
 'Boeing 757-300' 'Bombardier CL600 2D24' 'Boeing 737-924ER (WL)'
 'Airbus A320-232' 'Boeing 737-900ER and Airbus A320-200'
 'Cessna 208B Grand Caravan EX' 'Lockheed Martin C-130/L-100 Hercules'
 'Convair CV-440' 'Boeing B-17G Flying Fortress'
 'Honda Aircraft Company HondaJet HA-420' 'Saab 2000'
 'Canadair CL-600-2B19 Regional Jet CRJ-200LR' 'De Havilland DHC8-400'
 'Embraer EMB135' 'Cirrus Design Corporation SF50 Vision '
 'Pilatus Flugzeugwerke AG PC-24' 'Gulfstream Aerospace Corp Astra/G100']


Registration
 ['N398J' 'N509FN' 'N801DS' ... 'N31136' 'N607MM' 'N716VL']


Operator
 [nan 'Servant Air' 'Alan Robinson' ... 'Spring Mountain Raceway LLC'
 'Blue Ridge Helicopters Inc' 'Central Air Southwest']


StateOfOperator
 [nan 'USA' 'EGY' 'FRA' 'MAR' 'TWN' 'GBR' 'CAN' 'AUS' 'PHL' 'RUS' 'CHN'
 'DEU' 'KOR' 'TZA' 'FIN' 'IND' 'JOR' 'KEN' 'POL' 'LAO' 'IRL' 'SWE' 'KWT'
 'USA/USA' 'UAS']


StateOfRegistry
 ['USA' 'CHN' 'BHS' 'CAN' 'MEX' 'MAR' 'HTI' 'GBR' 'FRA' 'PHL' 'POL' 'RUS'
 'DEU' 'TCA' 'KOR' 'FIN' 'IND' 'JOR' 'VEN' 'QAT' 'IRL' 'EGY' 'KWT' 'AUS'
 nan]


FlightPhase
 ['Standing' 'Take-off' 'En route' 'Landing' 'Approach' 'Manoeuvring'
 'Unknown' 'Taxi' 'Initial Climb' nan]


Class
 ['Accident']


Fatalities
 [ 1.  6.  0.  4.  2.  3.  5.  7.  8.  9. 10. 50. 14. nan 11.]


Over2250
 [ True False]


Over5700
 [False nan True]


ScheduledCommercial
 [nan False True]


InjuryLevel
 ['Fatal' nan 'Serious' 'Minor' 'Unknown']


TypeDesignator
 ['PC12' 'PA47' 'RAV3' 'PA46' 'R22' 'A319' 'C340' 'P39' 'ST75' 'CRJ7'
 'B190' 'R44' 'C208' 'STAR' 'NAVI' 'BE58' 'EPIC' 'GLF2' 'LJ35' 'BE9L'
 'SBR2' 'C525' 'AC11' 'B36T' 'PA31' 'PA34' 'VAMP' 'SW3' 'AS50' 'DH90'
 'PA44' 'H500' 'C425' 'E145' 'C414' 'E170' 'TEX2' 'B37M' 'BE55' 'H269'
 'B25' 'EBOY' 'C172' 'C500' 'S58P' 'C402' 'AT6T' 'AT3P' 'G164' 'SS2P'
 'G64T' 'XV15' 'C750' 'H25C' 'B38M' 'WW23' 'CL60' 'G159' 'H25B' 'C310'
 'T6' 'E110' 'W201' 'C560' 'EN28' 'C421' 'AT3T' 'U21' 'TAYA' 'T34P' 'AT5T'
 'DH83' 'YALE' 'BE65' 'S38' 'EC35' 'DH88' 'B350' 'C21T' 'BE20' 'HAWK'
 'PC9' 'TBM7' 'MU2' 'S76' 'AC90' 'BE18' 'B407' 'A3' 'P46T' 'DC10' 'BE10'
 'BE99' 'AE45' 'T2' 'EN48' 'DHC1' 'J328' 'C25B' 'AC95' 'SS2T' 'C441' 'DW1'
 'L410' 'HPZL' 'EA50' 'SX30' 'RALL' 'C551' 'BE9T' 'DOVE' 'MS25' 'AT8T'
 'H21' 'DH87' 'DH82' 'CVLP' 'P2' 'TEAL' 'LJ60' 'ALO3' 'C320' 'C56X' 'B222'
 'A320' 'C212' 'VF60' 'C680' 'CRJX' 'BE35' 'FLAM' 'B60T' 'HAR' 'MU30'
 'KMAX' 'FA20' 'DC85' 'LJ45' 'AT43' 'F4' 'PC6P' 'M20T' 'LJ55' 'S39' 'MD90'
 'WP40' 'S64' 'E75L' 'DH89' 'C17' 'P63' 'P180' 'M326' 'EC20' 'C04T' 'YK11'
 'A109' 'MOSQ' 'F15' 'NORS' 'B18T' 'B212' 'S55P' 'DH8C' 'EC30' 'BN2T'
 'G44' 'SC7' 'AEST' 'MD60' 'A119' 'U16' 'HA4T' 'ST10' 'C02T' 'SW2' 'RV8'
 'CA8' 'ERCO' 'RV4' 'C182' 'M20P' 'L8' 'B47G' 'C150' 'N262' 'VK3P' 'CJ6'
 'B14C' 'YK52' 'E120' 'FOUG' 'C210' 'MRJ9' 'GLEX' 'C185' 'CA7T' 'HCAT'
 'BE24' 'T33' 'C303' 'P220' 'BE36' 'C206' 'XAIR' 'ECHO' 'DC93' 'P1' 'NDIC'
 'KRIC' 'LNP4' 'SREY' 'C152' 'C120' 'DA40' 'FFLY' 'RV6' 'M7' 'M5' 'SF34'
 'C170' 'C404' 'LA4' 'CH7B' 'FOX' 'F18H' 'GC1' 'AS65' 'BE76' 'S1' 'O1'
 'AS20' 'H12T' 'BL8' 'COL4' 'T206' 'LGEZ' 'FA10' 'CAMP' 'AR6T' 'C140'
 'COY2' 'RODS' 'PTS2' 'RV9' 'C180' 'C295' 'C337' 'A321' 'CH7A' 'B47T'
 'JACE' 'ION' 'KR1' 'L11' 'PP3' 'UH1' 'UH12' 'C175' 'DH80' 'BE23' 'LNCE'
 'CH60' 'BE33' 'HUSK' 'AS22' 'AS31' 'BRB2' 'DC87' 'C130' 'SG37' 'G96'
 'CH70' 'BROU' 'M200' 'C188' 'AA1' 'T18' 'AVID' 'LNC2' 'C177' 'OMLA'
 'F900' 'WHK2' 'E50P' 'AS55' 'B412' 'CRJ9' 'GLF6' 'VTOR' 'E135' 'ASTO'
 'AS32' 'BK17' 'LNC4' 'M4' 'PT22' 'C06T' 'BCS3' 'CA12' 'M7T' 'CLDS' 'C133'
 'E190' 'C195' 'STRK' 'G2T1' 'LJ70' 'R66' 'DC4' 'WACF' 'TIPB' 'B230'
 'TWEN' 'P210' 'BE30' 'P28A' 'EGRT' 'GALX' 'RS12' 'AC6L' 'L200' 'CL35'
 'A332' 'TAIL' 'A30B' 'TB20' 'GLF4' 'DC91' 'C25A' 'C700' 'TB31' 'C650'
 'I23' 'DHC5' 'F406' 'G150' 'MRAM' 'TR55' 'C14T' 'RC70' 'BE40' 'PAY4'

In [12]:
#checking for nulls
df.isnull().sum()

Date                      0
StateOfOccurrence         0
Location               2732
Model                   115
Registration              0
Operator                907
StateOfOperator        4202
StateOfRegistry           1
FlightPhase             100
Class                     0
Fatalities              114
Over2250                  0
Over5700                236
ScheduledCommercial     904
InjuryLevel            3160
TypeDesignator            0
Helicopter              260
Airplane                  0
Engines                   0
EngineType                0
Official               4231
OccCats                   0
Risk                   1082
Year                      0
dtype: int64

In [13]:
#copied dataframe
df1 = df.copy(deep = True )

### Filtering aircrafts and events

We want to filter the dataset to include aircraft that the client is interested in an analysis of:
- inspect relevant columns
- figure out any reasonable imputations
- filter the dataset

In [14]:
df1.head()

,Date,StateOfOccurrence,Location,Model,Registration,Operator,StateOfOperator,StateOfRegistry,FlightPhase,Class,...,InjuryLevel,TypeDesignator,Helicopter,Airplane,Engines,EngineType,Official,OccCats,Risk,Year
0,"""2008-01-03T00:00:00.000Z""",USA,Oklahoma City,PILATUS PC12,N398J,NaN,NaN,USA,Standing,Accident,...,Fatal,PC12,False,True,1,Turboprop,NaN,"[""RAMP""]",RS,2008
1,"""2008-01-05T00:00:00.000Z""",USA,Kodiak,PIPER PA31P 350,N509FN,Servant Air,NaN,USA,Take-off,Accident,...,Fatal,PA47,False,True,1,Jet,NaN,"[""LOC-I"",""SCF-NP""]",LOC-I,2008
2,"""2008-01-07T00:00:00.000Z""",USA,DeLand,NaN,N801DS,NaN,NaN,USA,En route,Accident,...,NaN,RAV3,False,True,1,Piston,NaN,"[""SCF-PP"",""F-NI""]",SCF,2008
3,"""2008-01-08T00:00:00.000Z""",USA,NaN,Piper Aircraft Inc PA-46 Malibu,N295S,Alan Robinson,NaN,USA,En route,Accident,...,NaN,PA46,False,True,1,Piston,NaN,[],TURB,2008
4,"""2008-01-08T00:00:00.000Z""",USA,NaN,Robinson Helicopter Company R22,N179SH,Silver State Helicopters Ltd,NaN,USA,En route,Accident,...,Serious,R22,True,False,1,Piston,NaN,[],NaN,2008

In [15]:
#identifying professional builds column data
df1[['EngineType', 'TypeDesignator', 'Model']]

     EngineType TypeDesignator                                       Model
0     Turboprop           PC12                                PILATUS PC12
1           Jet           PA47                             PIPER PA31P 350
2        Piston           RAV3                                         NaN
3        Piston           PA46             Piper Aircraft Inc PA-46 Malibu
4        Piston            R22             Robinson Helicopter Company R22
...         ...            ...                                         ...
4541     Piston            R44             Robinson Helicopter Company R44
4542     Piston            R22             Robinson Helicopter Company R22
4543     Piston            R44             Robinson Helicopter Company R44
4544     Piston           AC11  Twin Commander Aircraft LLC Twin Commander
4545     Piston           EBOY                               Bell Bell 206

[4546 rows x 3 columns]

In [16]:
#derive potential kewords for professoinal build planes
df1['Model'].unique()

array(['PILATUS PC12', 'PIPER PA31P 350', nan,
       'Piper Aircraft Inc PA-46 Malibu',
       'Robinson Helicopter Company R22', 'AIRBUS A319', 'CESSNA 340',
       'Bell Bell 206', 'BOEING 757 200',
       'CANADAIRREGIONAL JET SERIES 100/200', 'BEECH 1900',
       'Robinson Helicopter Company R44', 'CESSNA 208', 'RAYTHEON',
       'NORTH AMERICAN', 'BEECH G58', 'PIPER PA46 500TP',
       'Epic Aircraft LT/ Dynasty', 'Piper Aircraft Inc PA-31T',
       'GRUMMAN G21', 'Bell OH-58', 'LEARJET 35', 'BEECH 90',
       'Rockwell International Sabreliner', 'CESSNA 525 CITATIONJET',
       'ROCKWELL', 'Piper Aircraft Inc PA-31 Navajo',
       'Piper Aircraft Inc PA-34 Seneca', 'DE HAVILLAND DHC8',
       'SWEARINGENMERLIN IV A', 'Airbus Helicopters H125 / AS350',
       'DE HAVILLAND DHC2 I', 'Piper Aircraft Inc PA-44 Seminole',
       'MD Helicopters Inc MD500 / Hughes 369',
       'CESSNA 425 NO SERIES EXISTS', 'PIPER PA23 250',
       'EMBRAER EMB145 ER', 'CESSNA 414', 'EMBRAER ERJ170',
       'Beechcraft Corp Baron (Beech 58)', 'BOEING 737', 'BEECH 55',
       'Sikorsky (Schweizer) Hughes 269', 'CESSNA', 'CESSNA 500 CITATION',
       'SIKORSKY S58', 'CESSNA 402', 'AIR TRACTOR AT602 NO SERIES EXISTS',
       'AIR TRACTOR AT301', 'GRUMMAN G164', 'AYRES',
       'MD Helicopters Inc MD 600', 'SCHWEIZER', 'PIPER PA24',
       'Bell UH-1', 'CESSNA 750 NO SERIES EXISTS', 'RAYTHEON HAWKER',
       'FAIRCHILDSA227 III', 'BOEING 737 800', 'SIAI MARCHETTI',
       'CANADAIR CL600 1A11 600', 'Beechcraft Corp Beech 2000 Starship',
       'CESSNA 310', 'EMBRAER EMB110', 'WEATHERLY 620',
       'CESSNA 560 CITATION V',
       'Enstrom Helicopter Corporation Enstrom F-28', 'CESSNA 421',
       'AIR TRACTOR AT402', 'CCF', 'AIR TRACTOR AT502', 'DE HAVILLAND',
       'NORTH AMERICAN SNJ', 'BEECH 65',
       'Sikorsky Aircraft Corporation S-61', 'ROCKWELL 680',
       'Airbus Helicopters H135 / EC135', 'Beechcraft Corp Beech 99',
       'Hughes Helicopters MD500 / Hughes 369', 'AIR TRACTOR AT401',
       'Fairchild-Hiller Corp FH-1100', 'BEECH 200', 'HAWKER SIDDELEY',
       'Pilatus Flugzeugwerke AG PC-12', 'SOCATA TBM700', 'MITSUBISHI',
       'AYRES S2R600 T660', 'SIKORSKY S76', 'ROCKWELL 690', 'BEECH 18',
       'Bell Bell 407', 'MCDONNELL DOUGLAS DC10', 'BEECH 100',
       'DE HAVILLAND DHC6', 'BOEING 717 200', 'BEECH 99',
       'AERO VODOCHODY', 'SNOW',
       'Enstrom Helicopter Corporation Enstrom 480', 'BOEING 767 200',
       'Cessna Aircraft Company CJ3', 'CESSNA 441 NO SERIES EXISTS',
       'EAGLE DW1', 'PIPER PA31T 1',
       'Diamond Aircraft Industries GmbH DA42', 'PZL SWIDNIK',
       'Eclipse Aerospace Inc Eclipse 500', 'SWEARINGEN SX300',
       'BAE BAE125', 'CESSNA 551 CITATION II', 'SIKORSKY S61 N',
       'Enstrom Helicopter Corporation Enstrom 280',
       'MORANE SAULNIER MS760 A', 'AIR TRACTOR AT802', 'BOEING 777 300',
       'AIR TRACTOR AT400', 'VERTOL', 'DE HAVILLAND DH82 A', 'SWEARINGEN',
       'CONVAIR 580', 'LOCKHEED P2V', 'LEARJET 25', 'PIPER PA60 602P',
       'LEARJET 60', 'AEROSPATIALE SA365', 'CESSNA 320',
       'Cessna Aircraft Company Citation', 'BELL 222', 'PIPER PA28 201T',
       'Airbus A320', 'CASA C212', 'Vulcanair P.68',
       'CESSNA 680 NO SERIES EXISTS',
       'Bombardier (Canadair) CRJ Regional Jet', 'PIPER PA60',
       'PIPER PA28', 'BEECH 35', 'DASSAULT', 'BEECH 60', 'Bell Bell 222',
       'MCDONNELL DOUGLASDC-9-50', 'MITSUBISHI MU300',
       'Beechcraft Corp Beech 1900', 'CANADAIR CL600 2A12 600',
       'Cessna Aircraft Company Cessna 402', 'KAMAN K1200',
       'DASSAULT MYSTERE FALCON20', 'BELL 407', 'BOEING747-100/200 747',
       'MCDONNELL DOUGLASMD80 SERIES', 'BOEING 757 300', 'LEARJET 45',
       'AEROSPATIALE AS350', 'AIRBUS A320', 'ATR ATR42 300',
       'ROBINSON R22', 'Boeing (McDonnell-Douglas) DC-3',
       'DE HAVILLAND DHC8 400', 'PIPER PA31T', 'GRUMMAN', 'PIPER PA42',
       'LEARJET 55', 'Beechcraft Corp King Air 90',
       'Sikorsky Aircraft Corporation S-76', 'PIPER PA31',
       'CURTISS WRIGHT P40', 'SIKORSKY S64', 'Embraer 175',
       'DE HAVILLAND DHC2 III', 'BOEING 767 300',
       'Cessna Aircraft Company Cessna 441',
       'MCDONNELL DOUGLASDC-3 DAKOTA/C-47',
       'Rockwell International Turbo Commander',
       'Cessna Aircraft Company Cessna 421', 'MCDONNELL DOUGLAS DC10 30',
       'Piaggio Aerospace P180 Avanti', 'EMBRAER EMB135',
       'Airbus Helicopters H120', 'CESSNA 404 NO SERIES EXISTS',
       'YAKOVLEV YAK11', 'AGUSTA A109', 'AEROSPATIALE AS350 B2',
       'MCDONNELL DOUGLAS', 'EMBRAER ERJ175', 'NOORDUYN UC64',
       'BOEING 737 300', 'SIKORSKY S61', 'BELL 212', 'SIKORSKY S55',
       'DE HAVILLAND DHC8 300', 'De Havilland Canada DHC-8',
       'Airbus Helicopters H145 / EC145',
       'Britten-Norman Aircraft Ltd BN-2', 'Airbus Helicopters Bo105',
       'Beechcraft Corp King Air 200', 'LEARJET 36', 'GRUMMAN G44',
       'SHORT SC7', 'AEROSTAR AEROSTAR601', 'MD Helicopters Inc MD 520N',
       'AGUSTA A119', 'BOEING 767 400', 'MCDONNELL DOUGLAS MD90 30',
       'GRUMMAN G111', 'Fairchild (Swearingen) Merlin III',
       'Mitsubishi Aircraft Corporation MU-2',
       'Daher-Socata TBM 700 / 850 / 900', 'SWEARINGEN SA226 TC',
       'BELL 206', 'PIPER PA32', 'HUGHES 369', 'VANS RV8',
       'AIRBORNE XT582', 'ERCOUPE G', 'VANS RV4', 'CESSNA 182',
       'MOONEY M20', 'MITSUBISHI MU2B 60', 'CESSNA T41', 'LUSCOMBE 8',
       'RAYTHEON1900', 'BELL 47G 4A', 'AEROSTAR AEROSTAR601 P',
       'CESSNA 150', 'BELL 206 L', 'AEROSPATIALE', 'SCHWEIZER SGS232',
       'CIRRUS SR22 NO SERIES EXISTS', 'CIRRUS SR20 NO SERIES EXISTS',
       'PIPER PA25', 'NANCHANG CJ6 A', 'BELLANCA', 'YAKOVLEV YAK52',
       'EUROCOPTER EC135', 'EMBRAER EMB120', 'AIR FOUGA CM170',
       'CESSNA 210', 'PIPER PA46', 'BOMBARDIER BD700 1A11', 'CESSNA 185',
       'GRUMMAN AA5', 'BEECH 24', 'PIAGGIO P180 AVANTI',
       'EIPPER QUICKSILVER', 'BOEING 747 400',
       'CESSNA T303 NO SERIES EXISTS', 'EVEKTOR AEROTECHNIK', 'BEECH 36',
       'CESSNA 206', 'MD HELICOPTER 500', 'TECNAM P92 EA', 'KAWASAKI',
       'BRITTEN NORMAN BN2A', 'ROLLADEN SCHNEIDER LS4', 'LANCAIR IV P',
       'PROGRESSIVE AERODYNE SEAREY NO SERIES EXISTS', 'Learjet 35A',
       'CESSNA 152', 'CESSNA 120 NO SERIES EXISTS', 'PIPER PA34',
       'DIAMOND DA20', 'BALLOON WORKS FIREFLY8B', 'MITSUBISHI MU2',
       'VANS RV6 A', 'MAULE M7 235', 'VANS RV6', 'MAULE M5 220',
       'SAAB 340', 'CESSNA 170', 'LAKE LA4', 'GRUMMAN G1159',
       'CHAMPION 7GC', 'DENNEY KITFOX', 'PIPER PA44', 'PIPER J3C',
       'GLOBE', 'AEROSPATIALE SA366', 'BEECH 76 NO SERIES EXISTS',
       'INTERSTATE S1A', 'CESSNA 305', 'SCHLEICHER ASW20', 'HILLER UH12',
       'PIPER PA18', 'ROBINSON R44', 'CHAMPION 7GCB', 'CHAMPION',
       'RUTAN LONGEZ', 'AYRES S2R T',
       'BOMBARDIERCL-600 Regional Jet CRJ-1000', 'SCHWEIZER SGS136',
       'DASSAULT FALCON10', 'PIETENPOL AIRCAMPER', 'AERONCA',
       'CESSNA 140', 'RANS S6 ES', 'VANS RV4 UNDESIGNATED SERIES',
       'PITTS S2', 'BELL 206 B', 'PIPER PA22', 'PIPER PA20',
       'EIPPER QUICKSILVER MXII', 'VANS RV9 A', 'CESSNA 180',
       'MOONEY M20M', 'PIPER PA28 140', 'STEARMAN A75 L300',
       'AIRBUS A330 300', 'CESSNA 337', 'AIRBUS A321', 'CHAMPION 7EC',
       'Air Tractor Inc AT-602', 'STEARMAN B75 N1', 'BELL 47',
       'CORBEN BABYACE', 'RANS S6', 'AIR CREATION', 'LINDSTRAND LBL120A',
       'CESSNA 401', 'LUSCOMBE 11A', 'PIPER PA11', 'Boeing 737-832 (WL)',
       'AERONCA 7AC', 'PIPER J3C 65', 'PILATUS P3 NO SERIES EXISTS',
       'BELL UH1H', 'HILLER UH12E', 'CESSNA 175', 'STEARMAN A75 N1',
       'DE HAVILLAND L20A', 'BEECH 23 C23', 'LANCAIR IV',
       'ZENITH CH601 XL', 'DIAMOND DA20 C1', 'BEECH 33', 'AVIAT A1 B',
       'SCHLEICHER ASW27', 'SCHLEICHER ASW20L NO SERIES EXISTS',
       'BRANTLY B2', 'CESSNA 172 F', 'ERCOUPE 415', 'GRUMMAN G164 B',
       'SCHWEIZER SGS126', 'PIPER PA28R', 'CESSNA 172 N',
       'ZENAIR STOL CH701', 'MAX HOLSTE MH1521', 'PIPER PA14',
       'NORD 3200', 'CESSNA 188', 'AMERICAN AVIATION AA1',
       'Air Tractor Inc AT-500', 'THORP T18', 'AVID', 'LANCAIR 320',
       'GULFSTREAM GIV', 'Beechcraft Corp Premier I',
       'AEROSPATIALE AS350 B3', 'PIPER PA36', 'ZENAIR CH601 HD',
       'AIR TRACTOR AT602', 'SCHWEIZER SGS233', 'LINDSTRAND LBL69A',
       'STEARMAN PT13 B', 'CESSNA 177', 'GLASER DIRKS DG300',
       'Fairchild C-123K Provider', 'Daher-Socata Kodiak 100',
       'Dassault Aviation Falcon 900', 'Air Tractor Inc AT-802',
       'Viking Air DHC-3',
       'Scaled Composites LLC White Knight Two (Model 348)',
       'Piper Aircraft Inc PA-42', 'Airbus Helicopters Lama SA315B',
       'Embraer Phenom 100', 'Hawker Beechcraft 1900',
       'Airbus Helicopters AS355', 'Bell Bell 412',
       'Bombardier (Canadair) CRJ900 Regional Jet',
       'Cessna Aircraft Company Cessna 425',
       'Airbus Helicopters H130 / EC130',
       'Cessna Aircraft Company Citation II',
       'Gulfstream Aerospace Corp Gulfstream IV', 'BOMBARDIER',
       'Cessna Aircraft Company Cessna 404',
       'Beechcraft Corp King Air 100',
       'Cessna Aircraft Company Cessna 340',
       'Bombardier (Learjet) Learjet 25',
       'Bombardier (Canadair) CRJ700 Regional Jet', 'BEECH 300',
       'Tecnam P2006', 'MBB BK117', 'BELLANCA 1419 3',
       'LANCAIR LC41 550FG', 'MAULE M4', 'ROCKWELL S2R', 'RYAN PT22',
       'BEECH 23', 'PIPER PA18 150', 'DIAMOND DA20 A1', 'CONVAIR 340',
       'CESSNA 182 R', 'Dassault Aviation Falcon 20/200', 'MOONEY M20R',
       'PIPER PA30', 'MCDONNELL DOUGLAS 369 F', 'MCDONNELL DOUGLAS MD90',
       'POTEZ AIR FOUGA CM170', 'Bombardier CRJ200', 'BELLANCA 1419',
       'CHAMPION 8GCBC', 'AIRBORNE XT912', 'TAYLORCRAFT BC12',
       'MOONEY M20K', 'REARWIN 8135', 'DOUGLAS DC9 80', 'MOONEY M20F',
       'EMBRAER-ERJ190-100IGW', 'CESSNA 195', 'LANCAIR 360',
       'ENSTROM F28', 'BAC 167', 'GREAT LAKES', 'BEECH 35 G35',
       'ERJ-145(HARBIN EMBRAER)', 'RAND ROBINSON KR2', 'DOUGLAS',
       'EUROCOPTER EC130', 'WACO UPF7', 'GLASER DIRKS DG500 TRAINER',
       'CESSNA 414 UNDESIGNATED SERIES', 'BELLANCA 1413 2',
       'DE HAVILLAND DHC3', 'BELL 230', 'TECNAM', 'CESSNA P210 N',
       'GLASFLUGEL H301', 'AIRBUS A300 600', 'CIRRUS SR22',
       'CESSNA 188 B', 'GROB G102 ASTIR CS', 'PIPER PA38', 'GULFSTREAM',
       'CESSNA 172', 'RANS S12 XL', 'NORTH AMERICAN NAVION', 'AVIAT A1',
       'BELL 47G', 'PIPER PA12', 'LET L33', 'BOMBARDIER-CRJ-700',
       'AIRBUS A380', 'PZL MIELEC AN2', 'BOEING 777 200', 'HEINTZ ZENITH',
       'BEECH 45', 'RANS S12', 'WITTMAN W8',
       'Cessna Aircraft Company Cessna 414', 'BOEING 707',
       'GULFSTREAM GV', 'Bombardier CRJ-900', 'Douglas DC-6BF',
       'Cessna Aircraft Company CJ2', 'Bell Bell 212',
       'Boeing 767-332ER (WL)', 'Sikorsky Aircraft Corporation S-55',
       'Sikorsky Aircraft Corporation S-58',
       'Cessna Aircraft Company 208', 'Bell Bell 205',
       'Robinson Helicopter Company R66',
       'Bombardier (Learjet) Learjet 60', 'Airbus A320-211',
       'Cessna Aircraft Company Citation S/II',
       'Cessna Aircraft Company Cessna 401', 'Airbus Helicopters BK117',
       'Boeing 747', 'Bell Bell 230', 'Boeing 757-351 (WL)',
       'Boeing 737-732 (WL)', 'CESSNA 650 CITATION VII',
       'Leonardo (PZL-Swidnik) SW-4', 'DHC8',
       'Cessna Aircraft Company Citation V',
       'Reims Aviation S.A. 406 Caravan II',
       'Gulfstream Aerospace Corp Gulfstream G150', 'An-124',
       'Bombardier (Learjet) Learjet 35', 'CL-600',
       'Bombardier (Learjet) Learjet 31',
       'Bombardier (Learjet) Learjet 55', '737-800', '737-700', 'A321',
       '767-400', 'Embraer 170', 'Bell AH-1',
       'Mitsubishi Aircraft Corporation MU-300 Diamond', 'DHC8-400',
       'A319', 'Cessna Aircraft Company Citation XLS',
       'Viking Air SC.7 Skyvan', 'Viking Air Short 360 (SD3-60)',
       'Bombardier (Canadair) Challenger 600 / 601 / 604 / 605',
       '747-400', '135', 'Lockheed SP-2H Neptune',
       'Lockheed P-2H Neptune', 'Bell Bell 427', '757-200', 'A320',
       'Cessna Aircraft Company Citation Excel',
       'Israel Aerospace Industries Ltd Westwind',
       'Hawker Beechcraft Corp Hawker 400 / Beechjet 400',
       'DHC-8-402Q Dash 8', 'Viking Air DHC-2',
       'Airbus Helicopters Alouette 2', 'Leonardo (AgustaWestland) AW109',
       'CRJ-700', 'EMB-170', 'Bell Bell 214', 'AIRBUS A330',
       'Cessna Aircraft Company CJ1', 'A330-300',
       'Bombardier (Learjet) Learjet 36', '717-200', '737-300',
       'Leonardo (AgustaWestland) AW119',
       'Leonardo (AgustaWestland) AW139',
       'Pilatus Flugzeugwerke AG PC-6 Turbo Porter',
       'Fairchild (Swearingen) Metro', 'CRJ',
       'Cessna Aircraft Company Citation Encore', 'MD-11', 'EMB-145',
       'Boeing 777', 'McDonnell Douglas MD-11', 'Embraer ERJ-145',
       'EMBRAER ERJ190', 'BOEING 757', 'Boeing 757', 'BEECH 1900 C',
       'CESSNA 402 C', 'Airbus A321', 'Embraer EMB-170',
       'Bombardier CRJ-200', 'Bombardier Dash 8',
       'McDonnel Douglas MD-88', 'Kaman Aerospace K-1200', 'Boeing 737',
       'Canadair CL-600-2A12 Challenger 601', 'EMBRAER', 'Airbus A300',
       'Beechcraft 1900', 'Airbus Helicopters AS365',
       'Cessna 525A CitationJet CJ2+', 'Embraer EMB-500 Phenom 100',
       'Boeing 767', 'Beechcraft Corp King Air 350',
       'Douglas C-118A Liftmaster (DC-6A)', 'CESSNA 208 B',
       'Swearingen Metro', 'Bombardier (Learjet) Learjet 24',
       'Bell Bell 430', 'Gulfstream G200', 'McDonnell Douglas MD-88',
       'Douglas DC-9', 'Cessna 500 Citation I',
       'Cessna Aircraft Company Citation Sovereign', 'EMBRAER EMB140',
       'Pacific Aerospace Limited 750XL', 'Cessna Aircraft Company CJ4',
       'Airbus A330', 'Cessna 525 CitationJet CJ1', 'Boeing 737 NG',
       'Embraer ERJ-140', 'DHC-3T Texas Turbine Otter',
       'Swearingen SA226-AT Merlin IV', 'Cessna 208B Grand Caravan',
       'Gulfstream Aerospace Corp Gulfstream III', 'DHC-6 Twin Otter 300',
       'Embraer 145', 'Boeing 757-223 (WL)', 'Embraer Phenom 300',
       'AIRBUS A340 200', 'Hawker Beechcraft Corp 125/ Hawker',
       'Boeing 737-330 (SF)', 'Boeing 757-232 (WL)',
       'MD Helicopters Inc MD900 / MD902', 'CESSNA 441',
       'Viking Air DHC-6 Twin Otter', 'Embraer 190', 'BEECH 350',
       'Cessna 208B Super Cargomaster', 'GULFSTREAM GV SP G550',
       'EUROCOPTER EC130 B4', 'CESSNA 414 A', 'MBB BK117 C', 'EUROCOPTER',
       'Hawker Beechcraft Corp Hawker 4000', 'LEARJET 35 A',
       'SHORT SD360 SHERPA VARIANT100', 'Beech 99',
       'CANADAIR CL600 2B16 600', 'IAI 1125', 'CESSNA 560 XL',
       'BEECH C90', 'DASSAULT FALCON2000', 'Cessna 550 Citation II',
       'Bombardier BD-100-1A10 Challenger 300', 'Cessna 525 CitationJet',
       'Boeing 787', 'HAWKER SIDDELEY HS125', 'Airbus A319',
       'SINO SWEARINGEN SJ30', 'HAWKER 400',
       'Canadair CL-600-2C10 Regional Jet CRJ-702', 'EMBRAER ERJ170 100',
       'CESSNA 525', 'MCDONNELL DOUGLAS MD88 80', 'BOEING 737 700',
       'Guimbal Helicopters Cabri G2',
       'Enstrom Helicopter Corporation Enstrom TH180', 'LOCKHEED 382 G',
       'SWEARINGEN SA226 TB', 'EMBRAER EMB145 MP', 'BEECH 400 A',
       'Canadair CL-600-2B19 Regional Jet CRJ-200ER',
       'Cessna Aircraft Company Citation X', 'BOMBARDIER CL600 2B19 100',
       'Antonov An-2R', 'Airbus A321-211', 'AIRBUS A320 200',
       'AIRBUS A319 100', 'Bell Bell 429', 'BOEING 737 900',
       'Cessna Aircraft Company Citation Ultra', 'AIRBUS A321 200',
       'Bell Bell 525', 'DIAMOND DA40', 'Beechcraft B200 Super King Air',
       'Beechcraft C99 Commuter', 'BELL 429', 'BEECH', 'AGUSTA A109 S',
       'DE HAVILLAND DHC8 200', 'Cessna 208 Caravan I',
       'AIR TRACTOR AT502 B', 'NAMC YS-11', 'Airbus A380',
       'Boeing 737-823 (WL)', 'SWEARINGEN SA227 AC',
       'Beechcraft Corp Beech Duchess (Beech 76)',
       'Beechcraft Corp King Air 300', 'Boeing 737-700',
       'De Havilland Dash 8', 'Airbus A319-100',
       'Boeing (McDonnell-Douglas) MD-80', 'Boeing MD-83',
       'Swearingen SA226-TC Metro II', 'Beechcraft B200 King Air',
       'Embraer ERJ190', 'Beechcraft 99A Airliner',
       'Viking Air Short 330 (SD3-30)', 'Boeing 757-200',
       'Gulfstream Aerospace Corp G-73',
       'Cessna Aircraft Company Cessna 303', 'Airbus A321-200',
       'Bombardier CL 600 2C10', 'Embraer ERJ 170',
       'Fairchild (Swearingen) Merlin II',
       'Sikorsky Aircraft Corporation S-97', 'Airbus 330-300',
       'Lockheed P2V-5F Neptune', 'Boeing B737-800',
       'Aerostar Aircraft Corporation Aerostar', 'Bombardier CRJ700',
       'Cessna 680', 'Boeing MD90', 'Boeing 767-375ER',
       'Embraer EMB-120ER Brasilia', 'Airbus A321-231', 'Boeing 737-800',
       'Boeing B737-700', 'Boeing B767-300ER', 'Airbus A330-343',
       'Boeing B777', 'Boeing MD88', 'Embraer ERJ 700', 'Boeing DC-9',
       'BOEING 777', 'Swearingen SA227-AT Merlin IVC',
       'Twin Commander Aircraft LLC Twin Commander',
       'Sikorsky (Schweizer) 269D', 'AIRBUS A330 323',
       'CASA C-212 Aviocar 200', 'Cessna Aircraft Company Citation III',
       'BOEING 737 7H4', 'Bombardier CRJ-900LR (CL-600-2D24)',
       'BOEING 767 332; BOMBARDIER CL600 2D24', 'BOEING 737-8H4',
       'Boeing (McDonnell-Douglas) MD-11', 'Mahindra Aerospace GA10',
       'BOEING 787-9', 'Boeing 777 223', 'Curtiss C-46F-1-CU',
       'Douglas C-47B (DC-3)', 'Mcdonnell Douglas MD88',
       'Cessna 560 Citation Encore', 'Beechcraft B300 King Air 350',
       'Airbus A321-271N', 'Cessna Aircraft Company Citation Mustang',
       'British Aerospace BAe-125-700A', 'Embraer EMB-120 Brasilia',
       'Dassault Aviation Falcon 50', 'Beech 1900',
       'Cessna Aircraft Company Citation Latitude',
       'Bombardier CL 600 2B19', 'Embraer ERJ190-100', 'Airbus A320-200',
       'Boeing 727-200', 'Boeing 787-8', 'Convair C-131B Samaritan',
       'Embraer ERJ170', 'Boeing B777-200',
       'Sikorsky Aircraft Corporation S-70', 'Embraer EMB145',
       'Boeing 737-800 & Boeing 757-300',
       'Bombardier CL 600 2C10 & Bombardier CL600 2D24',
       'Bombardier CL-600-2C10 Regional Jet CRJ-702ER',
       'Bombardier CL-600-2D24 Regional Jet CRJ-900LR',
       'McDonnell Douglas MD88', 'Boeing 737-900',
       'Beechcraft Corp Beech Duke (Beech 60)', 'Mahindra Aerospace GA8',
       'Beechcraft B300 King Air 350i', 'Boeing 767-300',
       'Boeing 757-300', 'Bombardier CL600 2D24', 'Boeing 737-924ER (WL)',
       'Airbus A320-232', 'Boeing 737-900ER and Airbus A320-200',
       'Cessna 208B Grand Caravan EX',
       'Lockheed Martin C-130/L-100 Hercules', 'Convair CV-440',
       'Boeing B-17G Flying Fortress',
       'Honda Aircraft Company HondaJet HA-420', 'Saab 2000',
       'Canadair CL-600-2B19 Regional Jet CRJ-200LR',
       'De Havilland DHC8-400', 'Embraer EMB135',
       'Cirrus Design Corporation SF50 Vision ',
       'Pilatus Flugzeugwerke AG PC-24',
       'Gulfstream Aerospace Corp Astra/G100'], dtype=object)

In [17]:
#amature models to exclude
amateur_models = [
    'VANS RV4', 'VANS RV6', 'VANS RV6 A', 'VANS RV8',
    'VANS RV9 A', 'VANS RV4 UNDESIGNATED SERIES',
    'LANCAIR 320', 'LANCAIR 360', 'LANCAIR IV',
    'LANCAIR IV P', 'LANCAIR LC41 550FG',
    'RANS S6', 'RANS S6 ES', 'RANS S12', 'RANS S12 XL',
    'ZENAIR CH601 HD', 'ZENAIR STOL CH701',
    'ZENITH CH601 XL', 'HEINTZ ZENITH',
    'DENNEY KITFOX'
]

In [18]:
#applyinf filter

amateur = df1['Model'].isin(amateur_models)

df1 = df1[
    (df1['Airplane']   == True)  &   
    (df1['Helicopter'] == False) &   
    (~amateur)              &   
    (df1['Year']       >= 1983)      
].copy()

df1.shape

(3130, 24)

In [19]:
#check
df1.head()

,Date,StateOfOccurrence,Location,Model,Registration,Operator,StateOfOperator,StateOfRegistry,FlightPhase,Class,...,InjuryLevel,TypeDesignator,Helicopter,Airplane,Engines,EngineType,Official,OccCats,Risk,Year
0,"""2008-01-03T00:00:00.000Z""",USA,Oklahoma City,PILATUS PC12,N398J,NaN,NaN,USA,Standing,Accident,...,Fatal,PC12,False,True,1,Turboprop,NaN,"[""RAMP""]",RS,2008
1,"""2008-01-05T00:00:00.000Z""",USA,Kodiak,PIPER PA31P 350,N509FN,Servant Air,NaN,USA,Take-off,Accident,...,Fatal,PA47,False,True,1,Jet,NaN,"[""LOC-I"",""SCF-NP""]",LOC-I,2008
2,"""2008-01-07T00:00:00.000Z""",USA,DeLand,NaN,N801DS,NaN,NaN,USA,En route,Accident,...,NaN,RAV3,False,True,1,Piston,NaN,"[""SCF-PP"",""F-NI""]",SCF,2008
3,"""2008-01-08T00:00:00.000Z""",USA,NaN,Piper Aircraft Inc PA-46 Malibu,N295S,Alan Robinson,NaN,USA,En route,Accident,...,NaN,PA46,False,True,1,Piston,NaN,[],TURB,2008
7,"""2008-01-12T00:00:00.000Z""",USA,Port Clinton,CESSNA 340,N2637Y,Corporate American Operator,NaN,USA,Approach,Accident,...,Fatal,C340,False,True,2,Piston,NaN,"[""LOC-I""]",LOC-I,2008

### Cleaning and constructing Key Measurables

Injuries and robustness to destruction are a key interest point for the client. Clean and impute relevant columns and then create derived fields that best quantifies what the client wishes to track. **Use commenting or markdown to explain any cleaning assumptions as well as any derived columns you create.**

**Construct metric for fatal/serious injuries**

*Hint:* Estimate the total number of passengers on each flight. The likelihood of serious / fatal injury can be estimated as a fraction from this.

In [20]:

df1['SeriousFatalInjury'] = df1['InjuryLevel'].isin(['Fatal', 'Serious']).astype(int)

df1['SeriousFatalInjury'].value_counts()
df1.head()

,Date,StateOfOccurrence,Location,Model,Registration,Operator,StateOfOperator,StateOfRegistry,FlightPhase,Class,...,TypeDesignator,Helicopter,Airplane,Engines,EngineType,Official,OccCats,Risk,Year,SeriousFatalInjury
0,"""2008-01-03T00:00:00.000Z""",USA,Oklahoma City,PILATUS PC12,N398J,NaN,NaN,USA,Standing,Accident,...,PC12,False,True,1,Turboprop,NaN,"[""RAMP""]",RS,2008,1
1,"""2008-01-05T00:00:00.000Z""",USA,Kodiak,PIPER PA31P 350,N509FN,Servant Air,NaN,USA,Take-off,Accident,...,PA47,False,True,1,Jet,NaN,"[""LOC-I"",""SCF-NP""]",LOC-I,2008,1
2,"""2008-01-07T00:00:00.000Z""",USA,DeLand,NaN,N801DS,NaN,NaN,USA,En route,Accident,...,RAV3,False,True,1,Piston,NaN,"[""SCF-PP"",""F-NI""]",SCF,2008,0
3,"""2008-01-08T00:00:00.000Z""",USA,NaN,Piper Aircraft Inc PA-46 Malibu,N295S,Alan Robinson,NaN,USA,En route,Accident,...,PA46,False,True,1,Piston,NaN,[],TURB,2008,0
7,"""2008-01-12T00:00:00.000Z""",USA,Port Clinton,CESSNA 340,N2637Y,Corporate American Operator,NaN,USA,Approach,Accident,...,C340,False,True,2,Piston,NaN,"[""LOC-I""]",LOC-I,2008,1

In [21]:
meter = ['Fatalities', 'InjuryLevel', 'Over2250', 'Over5700', 'ScheduledCommercial']
df1[meter].isnull().sum

<bound method DataFrame.sum of       Fatalities  InjuryLevel  Over2250  Over5700  ScheduledCommercial
0          False        False     False     False                 True
1          False        False     False      True                False
2          False         True     False     False                 True
3          False         True     False     False                False
7          False        False     False      True                False
...          ...          ...       ...       ...                  ...
4538       False         True     False     False                False
4539       False         True     False     False                False
4540       False         True     False     False                False
4544       False         True     False     False                False
4545       False         True     False     False                False

[3130 rows x 5 columns]>

In [22]:
#clean injury level
df1['InjuryLevel']=df1['InjuryLevel'].fillna('None')
df1['InjuryLevel'].value_counts(dropna=False)

InjuryLevel
None       2225
Fatal       555
Serious     211
Minor       132
Unknown       7
Name: count, dtype: int64

In [23]:
#clean fatalities
fatal_median = df1.loc[df1['InjuryLevel'] == 'Fatal', 'Fatalities'].median()

#gather fatalities
def impute_fatalities(row):
    if pd.notnull(row['Fatalities']):
        return row['Fatalities']
    elif row['InjuryLevel'] in ['None', 'Minor']:
        return 0
    elif row['InjuryLevel'] == 'Fatal':
        return fatal_median
    else:
        return fatal_median
#apply by row
df1['Fatalities'] = df1.apply(impute_fatalities, axis=1)
#null confirmation
df1['Fatalities'].isnull().sum()

0

**Aircraft.Damage**
- identify and execute any cleaning tasks
- construct a derived column tracking whether an aircraft was destroyed or not.

### Investigate the *Make* column
- Identify cleaning tasks here
- List cleaning tasks clearly in markdown
- Execute the cleaning tasks
- For your analysis, keep Makes with a reasonable number (you can put the threshold at 50 though lower could work as well)

In [24]:
#clean occcats
#Occats are standard occurance codes isiued by the icao which may impy destruction
df1['OccCats'].isnull().sum()

0

In [25]:
#clean risk, UNK for unknown category which may be irrelevant
df1['Risk'] = df1['Risk'].fillna('UNK')
df1['Risk'].isnull().sum()

0

#### occarance codes in occats will be used to estimate aircraft damage
CFIT - Controlled Flight Into Terrain 
LOC-I - Loss of Control In-flight 
F-POST - Post impact fire 
F-NI - Fire/Smoke Non-Impact
MAC - Mid Air Collision

In [26]:

codes = {'CFIT', 'LOC-I', 'F-POST', 'F-NI', 'MAC'}

#rows risk asd fatal estimate to amount of damage
def destroyed(row):
    risk_destroyed = row['Risk'] in codes
    fatal_destroyed = (
        row['InjuryLevel'] == 'Fatal' and 
        row['Risk'] != 'RS'
    )
    return int(risk_destroyed or fatal_destroyed)

df1['Destroyed'] = df1.apply(destroyed, axis=1)

df1['Destroyed'].value_counts()

Destroyed
0    2579
1     551
Name: count, dtype: int64

In [27]:
#check
pd.crosstab(df1['Destroyed'], df1['InjuryLevel'])

InjuryLevel  Fatal  Minor  None  Serious  Unknown
Destroyed
0               52    123  2195      202        7
1              503      9    30        9        0

### Inspect Model column
- Get rid of any NaNs.
- Inspect the column and counts for each model/make. Are model labels unique to each make?
- If not, create a derived column that is a unique identifier for a given plane type.

##### Type designator will be used since its the closes unique identifier issued by the ICAO standard 
code in the file

In [28]:
#identify the nans
df1['Model'].isnull().sum()

115

In [29]:
#identify the nans
df1['TypeDesignator'].isnull().sum()

0

In [30]:
#clean model nans
df1['Model'] = df1['Model'].fillna(df1['TypeDesignator'])
df1['Model'].isnull().sum()

0

In [31]:
#locate values
model_disg = df1.groupby('Model')['TypeDesignator'].nunique()

models= model_disg[model_disg > 1].sort_values(ascending=False)
models.head(20)

Model
Cessna Aircraft Company Citation         7
Daher-Socata TBM 700 / 850 / 900         6
RAYTHEON                                 6
Air Tractor Inc AT-802                   6
Beechcraft Corp Beech 99                 6
ROCKWELL                                 5
DE HAVILLAND DHC2 I                      5
Pilatus Flugzeugwerke AG PC-12           5
NORTH AMERICAN                           5
Tecnam P2006                             5
Cessna Aircraft Company Citation II      5
Air Tractor Inc AT-602                   5
Air Tractor Inc AT-500                   5
BELL 206                                 4
Beechcraft Corp Premier I                4
DE HAVILLAND DHC6                        4
DHC-3T Texas Turbine Otter               3
RAYTHEON HAWKER                          3
Cessna Aircraft Company Citation S/II    3
CESSNA 206                               3
Name: TypeDesignator, dtype: int64

In [32]:
#get unique model names
df1[df1['Model'] == 'Cessna Aircraft Company Citation']['TypeDesignator'].value_counts()

TypeDesignator
C560    4
C56X    2
C525    2
C500    2
C650    1
C55B    1
C680    1
Name: count, dtype: int64

In [33]:
#plane uniquue idedntifier column
model_disg = df1.groupby('TypeDesignator')['Model'].nunique()

model = model_disg[model_disg > 1].sort_values(ascending=False)
model.head(20)

TypeDesignator
PA47    33
B37M    21
BE20    13
ST75    12
CRJX    11
B350    10
BE9L     8
C208     8
C560     7
C525     7
CL60     7
S38      7
P39      6
C500     5
LJ35     5
A320     5
P63      5
C17      5
C172     5
G164     5
Name: Model, dtype: int64

In [34]:
#verification
df1[df1['TypeDesignator'] == 'C208'][['TypeDesignator', 'Model']].value_counts()

TypeDesignator  Model
C208            Cessna Aircraft Company 208      51
                CESSNA 208                       17
                C208                             11
                Cessna 208B Grand Caravan         6
                CESSNA 208 B                      2
                Cessna 208 Caravan I              1
                Cessna 208B Grand Caravan EX      1
                Cessna 208B Super Cargomaster     1
Name: count, dtype: int64

### Cleaning other columns
- there are other columns containing data that might be related to the outcome of an accident. We list a few here:
- Engine.Type
- Number.of.Engines
- Broad.phase.of.flight

Inspect and identify potential cleaning tasks in each of the above columns. Execute those cleaning tasks. 

**Note**: You do not necessarily need to impute or drop NaNs here.

In [35]:
#cleaning engine type
df1['EngineType'].value_counts(dropna=False)

EngineType
Piston       1680
Turboprop     843
Jet           607
Name: count, dtype: int64

In [36]:
#cleaning engines
df1['Engines'].value_counts(dropna=False)

Engines
2    1664
1    1444
4      18
3       4
Name: count, dtype: int64

In [37]:
#clean flightphase, this too contains unknown values which may not be of any use
df1['FlightPhase'] = df1['FlightPhase'].fillna('Unknown')
df1['FlightPhase'].isnull().sum()

0

In [38]:
#clean ScheduledCommercial
df1['ScheduledCommercial'] = df1['ScheduledCommercial'].fillna(False)

df1['ScheduledCommercial'].isnull().sum()

0

In [39]:
#clean 57000 
df1['Over5700'] = df1['Over5700'].fillna(False)

df1['Over5700'].isnull().sum()

0

### Column Removal
- inspect the dataframe and drop any columns that have too many NaNs

### Save DataFrame to csv
- its generally useful to save data to file/server after its in a sufficiently cleaned or intermediate state
- the data can then be loaded directly in another notebook for further analysis
- this helps keep your notebooks and workflow readable, clean and modularized

In [40]:
df1.to_csv('Accidents_clean.csv', index=False)